M48
; DRILL file {KiCad 7.0.10} date Fri Dec 12 10:10:59 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-12T10:10:59-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.1024Y-3.778
X5.1024Y-4.0055
T2
X5.2303Y-3.8356
X5.2303Y-3.9537
M30
